### ISSUE TITLE
App closes immediately 

### ISSUE THREAD

**Issue by esambe** [Meherdeep/agora-group-calling#1]
App closes immediately when trying to join a call

**Comment by Meherdeep** [comment]
Hi @esambe,

I am sorry I haven't mentioned the details to run this project in the readme file. But you will need to follow the below given steps to run this app:

1. Go to [https://console.agora.io/](https://console.agora.io/) create an account with Agora, if you don't have one. 
2. Navigate to Project Management tab
3. Click on create and choose the option for just APP ID to test out the platform.

Once you have the APP ID inside go to [AppID.dart](https://github.com/Meherdeep/agora-group-calling/tree/master/lib/utils) and set

`var appID = '<----Insert your APP ID here---->';` 

This should work for you. Let me know if you face any other problem.

**Comment by Robert-D-Campbell** [comment]
I am having the same issue only on IOS devices. When I click to join, the app closes, works well with android though.

**Comment by Meherdeep** [comment]
Hey @Robert-D-Campbell,

Can you please share the logs and which iOS version are you running?
