### ISSUE TITLE
response.statusCode gives 404?

### ISSUE THREAD

**Issue by Muhammad-Ullah** [Meherdeep/agora-group-calling#7]
I am using this function to get the token, passing a random channel name but it gives error 404?
Future<void> getToken() async {
   final response = await http.get(
     Uri.parse(baseUrl + '/rtc/' + widget.channelName + '/publisher/uid/' + uid.toString()
          // To add expiry time uncomment the below given line with the time in seconds
          // + '?expiry=45'
          ),
    );

    if (response.statusCode == 200) {
      setState(() {
        token = response.body;
        token = jsonDecode(token)['rtcToken'];
      });
    } else {
      print('Failed to fetch the token');
    }
 }

**Comment by Meherdeep** [comment]
Please follow this guide to generate a token server: https://github.com/AgoraIO-Community/agora-token-service
